"use client"

/**
 * Single-user multi-device auth.
 *
 * The token is generated by the server at /api/setup or /api/pair and
 * returned to the client exactly once. The client persists it in
 * localStorage and includes it on every API request as a Bearer header.
 *
 * On Capacitor (iOS / Windows), the same token is mirrored into the
 * platform's SecureStorage (Keychain / Credential Manager) by a native
 * plugin; localStorage remains the runtime source of truth on web.
 */

const TOKEN_KEY = "pgd.token"
const DEVICE_NAME_KEY = "pgd.deviceName"

export function getToken(): string | null {
  if (typeof window === "undefined") return null
  try {
    return window.localStorage.getItem(TOKEN_KEY)
  } catch {
    return null
  }
}

export function setToken(token: string): void {
  if (typeof window === "undefined") return
  try {
    window.localStorage.setItem(TOKEN_KEY, token)
  } catch {
    // ignore (private mode etc.)
  }
}

export function clearToken(): void {
  if (typeof window === "undefined") return
  try {
    window.localStorage.removeItem(TOKEN_KEY)
    window.localStorage.removeItem(DEVICE_NAME_KEY)
  } catch {
    // ignore
  }
}

export function getDeviceName(): string | null {
  if (typeof window === "undefined") return null
  try {
    return window.localStorage.getItem(DEVICE_NAME_KEY)
  } catch {
    return null
  }
}

export function setDeviceName(name: string): void {
  if (typeof window === "undefined") return
  try {
    window.localStorage.setItem(DEVICE_NAME_KEY, name)
  } catch {
    // ignore
  }
}

export function hasToken(): boolean {
  return getToken() != null && getToken() !== ""
}